name: Generate GitHub Contribution Snake Game

on:
  schedule:
    # Запускается каждый день в 00:00 UTC (в 03:00 по Мск) для перерисовки
    - cron: "0 0 * * *"
  workflow_dispatch: # Позволяет запускать Action вручную во вкладке "Actions"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Даем разрешение на запись в репозиторий

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate GitHub Contribution Snake Game
        uses: Platane/snk@v3
        with:
          # GitHub username
          github_user_name: ${{ github.repository_owner }}
          # Чтобы файлы генерировались в папке 'outputs/'
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7fde

      - name: Push generated files to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
